# Generated by Django 3.1 on 2020-08-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.TextField(max_length=50, unique=True)),
                ('sn', models.TextField(max_length=50, unique=True)),
                ('vc', models.TextField(max_length=50, unique=True)),
                ('ac', models.TextField(max_length=50, unique=True)),
                ('vkey', models.TextField(max_length=50, unique=True)),
            ],
        ),
    ]
