# Generated by Django 3.1.1 on 2020-09-05 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finger',
            fields=[
                ('finger_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('finger_data', models.TextField(max_length=255)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
